name: PCB Android APK

on:
  push:
    branches: [ "main" ] # O "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # --- INICIO DE LOS CAMBIOS ---
    # Reemplaza 'nombre-de-tu-carpeta' con el nombre real de tu carpeta

    - name: Grant execute permission to gradlew
      run: chmod +x gradlew
      # Añade esta línea:
      working-directory: ./ReparadorAutorizadoFlutter-1.zip 

    - name: Build with Gradle
      run: ./gradlew assembleDebug
      # Añade esta línea:
      working-directory: ./ReparadorAutorizadoFlutter-1.zip

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        # Asegúrate de que la ruta 'path:' también incluya la carpeta
        path: ReparadorAutorizadoFlutter-1.zip/app/build/outputs/apk/debug/app-debug.apk
        
    # --- FIN DE LOS CAMBIOS ---
